/**
 * Mock Data for Storage Module
 *
 * Provides mock batch data for development and testing.
 * Used as fallback when GraphQL is unavailable.
 */

import type { StorageBatch } from "@/types/extended";

// ==========================================
// HELPER FUNCTIONS
// ==========================================

const today = new Date();

function formatDate(daysOffset: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString();
}

// ==========================================
// MOCK BATCHES DATA
// ==========================================

export const MOCK_BATCHES: StorageBatch[] = [
  // Сьогоднішні поставки
  {
    documentId: "batch_001",
    slug: "pork-shoulder-001",
    productId: "prod_001",
    productName: "Свинина (лопатка)",
    yieldProfileId: "yield_pork",
    grossIn: 25,
    unitCost: 185,
    totalCost: 4625,
    supplierId: "supplier_001",
    invoiceNumber: "INV-2024-1201",
    receivedAt: formatDate(0),
    expiryDate: formatDate(5),
    batchNumber: "B-001-1221",
    processes: [],
    netAvailable: 25,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  {
    documentId: "batch_002",
    slug: "chicken-whole-001",
    productId: "prod_003",
    productName: "Курка (ціла)",
    yieldProfileId: "yield_chicken",
    grossIn: 30,
    unitCost: 98,
    totalCost: 2940,
    supplierId: "supplier_002",
    invoiceNumber: "INV-2024-1202",
    receivedAt: formatDate(0),
    expiryDate: formatDate(4),
    batchNumber: "B-002-1221",
    processes: [],
    netAvailable: 30,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  {
    documentId: "batch_003",
    slug: "salmon-fillet-001",
    productId: "prod_005",
    productName: "Лосось (філе)",
    yieldProfileId: "yield_salmon",
    grossIn: 8,
    unitCost: 820,
    totalCost: 6560,
    supplierId: "supplier_003",
    invoiceNumber: "INV-2024-1203",
    receivedAt: formatDate(0),
    expiryDate: formatDate(3),
    batchNumber: "B-003-1221",
    processes: [],
    netAvailable: 8,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  {
    documentId: "batch_004",
    slug: "potato-001",
    productId: "prod_007",
    productName: "Картопля",
    yieldProfileId: "yield_potato",
    grossIn: 50,
    unitCost: 18,
    totalCost: 900,
    supplierId: "supplier_004",
    invoiceNumber: "INV-2024-1204",
    receivedAt: formatDate(0),
    expiryDate: formatDate(30),
    batchNumber: "B-004-1221",
    processes: [],
    netAvailable: 50,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  {
    documentId: "batch_005",
    slug: "tomatoes-001",
    productId: "prod_010",
    productName: "Помідори",
    yieldProfileId: "yield_potato",
    grossIn: 15,
    unitCost: 95,
    totalCost: 1425,
    supplierId: "supplier_004",
    invoiceNumber: "INV-2024-1205",
    receivedAt: formatDate(0),
    expiryDate: formatDate(7),
    batchNumber: "B-005-1221",
    processes: [],
    netAvailable: 15,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  // Вчорашні (частково оброблені)
  {
    documentId: "batch_006",
    slug: "beef-tenderloin-001",
    productId: "prod_002",
    productName: "Яловичина (вирізка)",
    yieldProfileId: "yield_beef",
    grossIn: 12,
    unitCost: 480,
    totalCost: 5760,
    supplierId: "supplier_001",
    invoiceNumber: "INV-2024-1195",
    receivedAt: formatDate(-1),
    expiryDate: formatDate(4),
    batchNumber: "B-006-1220",
    processes: [
      {
        documentId: "proc_001",
        processType: "portioning",
        processedAt: formatDate(-1),
        operatorId: "chef_001",
        operatorName: "Олександр К.",
        grossInput: 12,
        netOutput: 8.64,
        wasteOutput: 3.36,
        expectedYield: 0.72,
        actualYield: 0.72,
        variancePercent: 0,
      },
    ],
    netAvailable: 6.5,
    usedAmount: 2.14,
    wastedAmount: 3.36,
    status: "in_use",
  },
  {
    documentId: "batch_007",
    slug: "duck-whole-001",
    productId: "prod_004",
    productName: "Качка (ціла)",
    yieldProfileId: "yield_duck",
    grossIn: 8,
    unitCost: 290,
    totalCost: 2320,
    supplierId: "supplier_002",
    invoiceNumber: "INV-2024-1196",
    receivedAt: formatDate(-1),
    expiryDate: formatDate(3),
    batchNumber: "B-007-1220",
    processes: [],
    netAvailable: 8,
    usedAmount: 0,
    wastedAmount: 0,
    status: "available",
  },
  // Позавчорашні
  {
    documentId: "batch_008",
    slug: "shrimp-001",
    productId: "prod_006",
    productName: "Креветки тигрові",
    yieldProfileId: "yield_shrimp",
    grossIn: 5,
    unitCost: 520,
    totalCost: 2600,
    supplierId: "supplier_003",
    invoiceNumber: "INV-2024-1190",
    receivedAt: formatDate(-2),
    expiryDate: formatDate(0),
    batchNumber: "B-008-1219",
    processes: [
      {
        documentId: "proc_002",
        processType: "cleaning",
        processedAt: formatDate(-2),
        operatorId: "chef_002",
        operatorName: "Марія С.",
        grossInput: 5,
        netOutput: 2.25,
        wasteOutput: 2.75,
        expectedYield: 0.45,
        actualYield: 0.45,
        variancePercent: 0,
      },
    ],
    netAvailable: 0.5,
    usedAmount: 1.75,
    wastedAmount: 2.75,
    status: "in_use",
  },
  // === ДОДАТКОВІ ПАРТІЇ ===
  // Молочні продукти
  {
    documentId: "batch_009",
    slug: "butter-001",
    productId: "prod_020",
    productName: "Вершкове масло 82.5%",
    yieldProfileId: "yield_dairy",
    grossIn: 10,
    unitCost: 280,
    totalCost: 2800,
    supplierId: "supplier_005",
    invoiceNumber: "INV-2024-1206",
    receivedAt: formatDate(0),
    expiryDate: formatDate(30),
    batchNumber: "B-009-1221",
    processes: [],
    netAvailable: 10,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  {
    documentId: "batch_010",
    slug: "cream-001",
    productId: "prod_021",
    productName: "Вершки 33%",
    yieldProfileId: "yield_dairy",
    grossIn: 20,
    unitCost: 120,
    totalCost: 2400,
    supplierId: "supplier_005",
    invoiceNumber: "INV-2024-1207",
    receivedAt: formatDate(0),
    expiryDate: formatDate(10),
    batchNumber: "B-010-1221",
    processes: [],
    netAvailable: 20,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  {
    documentId: "batch_011",
    slug: "parmesan-001",
    productId: "prod_022",
    productName: "Пармезан",
    yieldProfileId: "yield_cheese",
    grossIn: 5,
    unitCost: 850,
    totalCost: 4250,
    supplierId: "supplier_005",
    invoiceNumber: "INV-2024-1208",
    receivedAt: formatDate(-1),
    expiryDate: formatDate(60),
    batchNumber: "B-011-1220",
    processes: [],
    netAvailable: 4.2,
    usedAmount: 0.8,
    wastedAmount: 0,
    status: "in_use",
  },
  // Овочі
  {
    documentId: "batch_012",
    slug: "onions-001",
    productId: "prod_008",
    productName: "Цибуля ріпчаста",
    yieldProfileId: "yield_onion",
    grossIn: 30,
    unitCost: 25,
    totalCost: 750,
    supplierId: "supplier_004",
    invoiceNumber: "INV-2024-1209",
    receivedAt: formatDate(0),
    expiryDate: formatDate(30),
    batchNumber: "B-012-1221",
    processes: [],
    netAvailable: 30,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  {
    documentId: "batch_013",
    slug: "carrots-001",
    productId: "prod_009",
    productName: "Морква",
    yieldProfileId: "yield_carrot",
    grossIn: 20,
    unitCost: 22,
    totalCost: 440,
    supplierId: "supplier_004",
    invoiceNumber: "INV-2024-1210",
    receivedAt: formatDate(-1),
    expiryDate: formatDate(14),
    batchNumber: "B-013-1220",
    processes: [],
    netAvailable: 18.5,
    usedAmount: 1.5,
    wastedAmount: 0,
    status: "in_use",
  },
  {
    documentId: "batch_014",
    slug: "lettuce-001",
    productId: "prod_011",
    productName: "Салат Айсберг",
    yieldProfileId: "yield_lettuce",
    grossIn: 10,
    unitCost: 85,
    totalCost: 850,
    supplierId: "supplier_004",
    invoiceNumber: "INV-2024-1211",
    receivedAt: formatDate(0),
    expiryDate: formatDate(5),
    batchNumber: "B-014-1221",
    processes: [],
    netAvailable: 10,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  {
    documentId: "batch_015",
    slug: "bell-pepper-001",
    productId: "prod_012",
    productName: "Перець болгарський",
    yieldProfileId: "yield_pepper",
    grossIn: 8,
    unitCost: 140,
    totalCost: 1120,
    supplierId: "supplier_004",
    invoiceNumber: "INV-2024-1212",
    receivedAt: formatDate(-1),
    expiryDate: formatDate(8),
    batchNumber: "B-015-1220",
    processes: [],
    netAvailable: 6.5,
    usedAmount: 1.5,
    wastedAmount: 0,
    status: "in_use",
  },
  // М'ясо та риба
  {
    documentId: "batch_016",
    slug: "ribeye-001",
    productId: "prod_013",
    productName: "Рібай стейк",
    yieldProfileId: "yield_beef",
    grossIn: 15,
    unitCost: 680,
    totalCost: 10200,
    supplierId: "supplier_001",
    invoiceNumber: "INV-2024-1213",
    receivedAt: formatDate(0),
    expiryDate: formatDate(7),
    batchNumber: "B-016-1221",
    processes: [],
    netAvailable: 15,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  {
    documentId: "batch_017",
    slug: "pork-ribs-001",
    productId: "prod_014",
    productName: "Свинячі ребра",
    yieldProfileId: "yield_pork",
    grossIn: 20,
    unitCost: 165,
    totalCost: 3300,
    supplierId: "supplier_001",
    invoiceNumber: "INV-2024-1214",
    receivedAt: formatDate(-1),
    expiryDate: formatDate(4),
    batchNumber: "B-017-1220",
    processes: [
      {
        documentId: "proc_003",
        processType: "cleaning",
        processedAt: formatDate(-1),
        operatorId: "chef_003",
        operatorName: "Сергій Я.",
        grossInput: 20,
        netOutput: 16,
        wasteOutput: 4,
        expectedYield: 0.80,
        actualYield: 0.80,
        variancePercent: 0,
      },
    ],
    netAvailable: 12,
    usedAmount: 4,
    wastedAmount: 4,
    status: "in_use",
  },
  {
    documentId: "batch_018",
    slug: "sea-bass-001",
    productId: "prod_015",
    productName: "Сібас (ціла)",
    yieldProfileId: "yield_seabass",
    grossIn: 10,
    unitCost: 420,
    totalCost: 4200,
    supplierId: "supplier_003",
    invoiceNumber: "INV-2024-1215",
    receivedAt: formatDate(0),
    expiryDate: formatDate(3),
    batchNumber: "B-018-1221",
    processes: [],
    netAvailable: 10,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  // Сухі продукти
  {
    documentId: "batch_019",
    slug: "pasta-001",
    productId: "prod_016",
    productName: "Спагетті №5",
    yieldProfileId: "yield_dry",
    grossIn: 20,
    unitCost: 65,
    totalCost: 1300,
    supplierId: "supplier_002",
    invoiceNumber: "INV-2024-1216",
    receivedAt: formatDate(-3),
    expiryDate: formatDate(365),
    batchNumber: "B-019-1218",
    processes: [],
    netAvailable: 18,
    usedAmount: 2,
    wastedAmount: 0,
    status: "in_use",
  },
  {
    documentId: "batch_020",
    slug: "rice-001",
    productId: "prod_017",
    productName: "Рис Арборіо",
    yieldProfileId: "yield_dry",
    grossIn: 10,
    unitCost: 120,
    totalCost: 1200,
    supplierId: "supplier_002",
    invoiceNumber: "INV-2024-1217",
    receivedAt: formatDate(-2),
    expiryDate: formatDate(180),
    batchNumber: "B-020-1219",
    processes: [],
    netAvailable: 9,
    usedAmount: 1,
    wastedAmount: 0,
    status: "in_use",
  },
  // Напої
  {
    documentId: "batch_021",
    slug: "coffee-001",
    productId: "prod_018",
    productName: "Кава в зернах",
    yieldProfileId: "yield_coffee",
    grossIn: 5,
    unitCost: 450,
    totalCost: 2250,
    supplierId: "supplier_002",
    invoiceNumber: "INV-2024-1218",
    receivedAt: formatDate(-1),
    expiryDate: formatDate(90),
    batchNumber: "B-021-1220",
    processes: [],
    netAvailable: 4.5,
    usedAmount: 0.5,
    wastedAmount: 0,
    status: "in_use",
  },
  {
    documentId: "batch_022",
    slug: "orange-juice-001",
    productId: "prod_019",
    productName: "Апельсини для фрешу",
    yieldProfileId: "yield_citrus",
    grossIn: 30,
    unitCost: 55,
    totalCost: 1650,
    supplierId: "supplier_004",
    invoiceNumber: "INV-2024-1219",
    receivedAt: formatDate(0),
    expiryDate: formatDate(7),
    batchNumber: "B-022-1221",
    processes: [],
    netAvailable: 30,
    usedAmount: 0,
    wastedAmount: 0,
    status: "received",
  },
  // Критичні/Попередження партії
  {
    documentId: "batch_023",
    slug: "mozzarella-001",
    productId: "prod_023",
    productName: "Моцарелла",
    yieldProfileId: "yield_cheese",
    grossIn: 5,
    unitCost: 320,
    totalCost: 1600,
    supplierId: "supplier_005",
    invoiceNumber: "INV-2024-1185",
    receivedAt: formatDate(-5),
    expiryDate: formatDate(1),
    batchNumber: "B-023-1216",
    processes: [],
    netAvailable: 1.2,
    usedAmount: 3.8,
    wastedAmount: 0,
    status: "in_use",
  },
  {
    documentId: "batch_024",
    slug: "basil-001",
    productId: "prod_024",
    productName: "Базилік свіжий",
    yieldProfileId: "yield_herbs",
    grossIn: 2,
    unitCost: 180,
    totalCost: 360,
    supplierId: "supplier_004",
    invoiceNumber: "INV-2024-1190",
    receivedAt: formatDate(-3),
    expiryDate: formatDate(0),
    batchNumber: "B-024-1218",
    processes: [],
    netAvailable: 0.3,
    usedAmount: 1.7,
    wastedAmount: 0,
    status: "in_use",
  },
  {
    documentId: "batch_025",
    slug: "eggs-001",
    productId: "prod_025",
    productName: "Яйця курячі С1",
    yieldProfileId: "yield_eggs",
    grossIn: 300,
    unitCost: 4.5,
    totalCost: 1350,
    supplierId: "supplier_005",
    invoiceNumber: "INV-2024-1200",
    receivedAt: formatDate(-2),
    expiryDate: formatDate(25),
    batchNumber: "B-025-1219",
    processes: [],
    netAvailable: 245,
    usedAmount: 55,
    wastedAmount: 0,
    status: "in_use",
  },
];
